// Copyright 2026 Paolo Vella
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

//! JSON, Markdown, and OCSF report generation.

use crate::BenchmarkResult;
use serde_json::json;

/// Generate a JSON report string.
pub fn to_json(result: &BenchmarkResult) -> String {
    match serde_json::to_string_pretty(result) {
        Ok(json) => json,
        Err(e) => {
            let escaped = e.to_string().replace('\\', "\\\\").replace('"', "\\\"");
            format!(
                "{{\"error\":\"failed to serialize benchmark result\",\"details\":\"{escaped}\"}}"
            )
        }
    }
}

/// Generate a Markdown report string.
pub fn to_markdown(result: &BenchmarkResult) -> String {
    let mut md = String::new();

    // Header
    md.push_str("# MCPSEC Benchmark Report\n\n");
    md.push_str(&format!(
        "**Framework:** {} v{}\n\n",
        result.framework, result.version
    ));
    md.push_str(&format!("**Gateway:** {}\n\n", result.gateway));
    md.push_str(&format!("**Timestamp:** {}\n\n", result.timestamp));

    // Overall score
    md.push_str("## Overall Score\n\n");
    md.push_str(&format!(
        "| Score | Tier | Tier Name |\n|-------|------|-----------|\n| {:.1}% | {} | {} |\n\n",
        result.overall_score, result.tier, result.tier_name
    ));

    // Summary
    md.push_str("## Summary\n\n");
    md.push_str(&format!(
        "| Total Tests | Passed | Failed | Skipped |\n|-------------|--------|--------|---------|\n| {} | {} | {} | {} |\n\n",
        result.summary.total_tests,
        result.summary.passed,
        result.summary.failed,
        result.summary.skipped
    ));

    // Property scores
    md.push_str("## Property Scores\n\n");
    md.push_str("| Property | Name | Score | Passed | Total |\n");
    md.push_str("|----------|------|-------|--------|-------|\n");
    for prop in &result.properties {
        md.push_str(&format!(
            "| {} | {} | {:.0}% | {} | {} |\n",
            prop.property_id, prop.name, prop.score, prop.tests_passed, prop.tests_total
        ));
    }
    md.push('\n');

    // Attack results by class
    md.push_str("## Attack Results\n\n");

    let mut current_class = String::new();
    for attack in &result.attacks {
        if attack.class != current_class {
            current_class = attack.class.clone();
            md.push_str(&format!("### {current_class}\n\n"));
            md.push_str("| ID | Name | Result | Latency |\n");
            md.push_str("|----|------|--------|---------|\n");
        }
        let status = if attack.passed { "PASS" } else { "**FAIL**" };
        let latency = format_latency(attack.latency_ns);
        md.push_str(&format!(
            "| {} | {} | {} | {} |\n",
            attack.attack_id, attack.name, status, latency
        ));
    }
    md.push('\n');

    // Failed tests detail with remediation guidance
    let failed: Vec<_> = result.attacks.iter().filter(|a| !a.passed).collect();
    if !failed.is_empty() {
        md.push_str("## Failed Tests\n\n");

        // Group failures by class prefix for remediation
        let mut seen_classes = std::collections::HashSet::new();

        for attack in &failed {
            md.push_str(&format!(
                "- **{}** ({}): {}\n",
                attack.attack_id, attack.name, attack.details
            ));
        }
        md.push('\n');

        // Add remediation guidance per class
        md.push_str("## Remediation Guidance\n\n");
        for attack in &failed {
            let prefix = attack
                .attack_id
                .split('.')
                .next()
                .unwrap_or(&attack.attack_id);
            if seen_classes.insert(prefix.to_string()) {
                let guidance = crate::remediation::guidance(&attack.attack_id);
                md.push_str(&format!("### {} ({})\n\n", prefix, attack.class));
                md.push_str(guidance);
                md.push_str("\n\n");
            }
        }
    }

    md.push_str("---\n\n");
    md.push_str("Generated by [MCPSEC](https://github.com/vellaveto/vellaveto/tree/main/mcpsec)\n");

    md
}

/// Generate an OCSF (Open Cybersecurity Schema Framework) report.
///
/// Each attack result maps to an OCSF Security Finding (class_uid=2001).
/// The overall benchmark maps to a Detection Finding activity.
/// See <https://schema.ocsf.io/1.1.0/classes/security_finding>
pub fn to_ocsf(result: &BenchmarkResult) -> String {
    let findings: Vec<serde_json::Value> = result
        .attacks
        .iter()
        .map(|attack| {
            let severity_id: u8 = if attack.passed { 1 } else { 4 }; // 1=Info, 4=High
            let status_id: u8 = if attack.passed { 1 } else { 2 }; // 1=New, 2=InProgress
            json!({
                "class_uid": 2001,
                "class_name": "Security Finding",
                "category_uid": 2,
                "category_name": "Findings",
                "activity_id": 1,
                "activity_name": "Create",
                "severity_id": severity_id,
                "status_id": status_id,
                "time": result.timestamp,
                "finding_info": {
                    "uid": attack.attack_id,
                    "title": attack.name,
                    "desc": attack.details,
                    "types": [attack.class.as_str()],
                    "data_sources": ["MCPSEC Benchmark"]
                },
                "metadata": {
                    "product": {
                        "name": "MCPSEC",
                        "version": result.version,
                        "vendor_name": "Vellaveto"
                    },
                    "version": "1.1.0"
                },
                "resources": [{
                    "name": result.gateway,
                    "type": "MCP Gateway"
                }],
                "unmapped": {
                    "attack_id": attack.attack_id,
                    "passed": attack.passed,
                    "latency_ns": attack.latency_ns,
                    "overall_score": result.overall_score,
                    "tier": result.tier,
                    "tier_name": result.tier_name
                }
            })
        })
        .collect();

    match serde_json::to_string_pretty(&findings) {
        Ok(json) => json,
        Err(e) => {
            let escaped = e.to_string().replace('\\', "\\\\").replace('"', "\\\"");
            format!("{{\"error\":\"failed to serialize OCSF report\",\"details\":\"{escaped}\"}}")
        }
    }
}

/// Generate a JUnit XML report for CI integration.
///
/// Maps attack tests to JUnit test cases. Failed attacks include the
/// failure details. Compatible with Jenkins, GitLab CI, GitHub Actions,
/// and other CI systems that parse JUnit XML.
pub fn to_junit(result: &BenchmarkResult) -> String {
    let mut xml = String::new();
    xml.push_str("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
    xml.push_str(&format!(
        "<testsuites name=\"MCPSEC\" tests=\"{}\" failures=\"{}\" time=\"{:.3}\">\n",
        result.summary.total_tests,
        result.summary.failed,
        total_time_secs(&result.attacks),
    ));

    // Group by class
    let mut current_class = String::new();
    let mut class_tests: Vec<&crate::AttackResult> = Vec::new();

    for attack in &result.attacks {
        if attack.class != current_class {
            if !class_tests.is_empty() {
                write_testsuite(&mut xml, &current_class, &class_tests);
                class_tests.clear();
            }
            current_class = attack.class.clone();
        }
        class_tests.push(attack);
    }
    if !class_tests.is_empty() {
        write_testsuite(&mut xml, &current_class, &class_tests);
    }

    xml.push_str("</testsuites>\n");
    xml
}

fn write_testsuite(xml: &mut String, class: &str, tests: &[&crate::AttackResult]) {
    let failures = tests.iter().filter(|t| !t.passed).count();
    let time = total_time_secs(tests.iter().copied());
    xml.push_str(&format!(
        "  <testsuite name=\"{class}\" tests=\"{}\" failures=\"{failures}\" time=\"{time:.3}\">\n",
        tests.len(),
    ));
    for test in tests {
        let time_s = test.latency_ns as f64 / 1_000_000_000.0;
        xml.push_str(&format!(
            "    <testcase name=\"{} — {}\" classname=\"mcpsec.{}\" time=\"{time_s:.6}\"",
            xml_escape(&test.attack_id),
            xml_escape(&test.name),
            xml_escape(&test.class),
        ));
        if test.passed {
            xml.push_str(" />\n");
        } else {
            xml.push_str(">\n");
            xml.push_str(&format!(
                "      <failure message=\"Attack not detected\">{}</failure>\n",
                xml_escape(&test.details),
            ));
            xml.push_str("    </testcase>\n");
        }
    }
    xml.push_str("  </testsuite>\n");
}

fn total_time_secs<'a>(attacks: impl IntoIterator<Item = &'a crate::AttackResult>) -> f64 {
    attacks
        .into_iter()
        .map(|a| a.latency_ns as f64 / 1_000_000_000.0)
        .sum()
}

fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&apos;")
}

fn format_latency(ns: u64) -> String {
    if ns < 1_000 {
        format!("{ns}ns")
    } else if ns < 1_000_000 {
        format!("{:.1}us", ns as f64 / 1_000.0)
    } else {
        format!("{:.1}ms", ns as f64 / 1_000_000.0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{AttackResult, BenchmarkResult, BenchmarkSummary, PropertyScore};

    fn sample_result() -> BenchmarkResult {
        BenchmarkResult {
            framework: "MCPSEC".to_string(),
            version: "1.0.0".to_string(),
            timestamp: "2026-02-15T12:00:00Z".to_string(),
            gateway: "test-gateway".to_string(),
            gateway_version: "1.0.0".to_string(),
            overall_score: 75.0,
            tier: 3,
            tier_name: "Strong".to_string(),
            properties: vec![PropertyScore {
                property_id: "P1".to_string(),
                name: "Tool-Level Access Control".to_string(),
                score: 100.0,
                tests_passed: 6,
                tests_total: 6,
            }],
            attacks: vec![
                AttackResult {
                    attack_id: "A1.1".to_string(),
                    name: "Classic injection phrase".to_string(),
                    class: "Prompt Injection Evasion".to_string(),
                    passed: true,
                    latency_ns: 28_000,
                    details: "Detected".to_string(),
                },
                AttackResult {
                    attack_id: "A1.2".to_string(),
                    name: "Zero-width evasion".to_string(),
                    class: "Prompt Injection Evasion".to_string(),
                    passed: false,
                    latency_ns: 150_000,
                    details: "Not detected".to_string(),
                },
            ],
            summary: BenchmarkSummary {
                total_tests: 2,
                passed: 1,
                failed: 1,
                skipped: 0,
            },
        }
    }

    #[test]
    fn test_json_roundtrip() {
        let result = sample_result();
        let json = to_json(&result);
        let parsed: BenchmarkResult = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.framework, "MCPSEC");
        assert_eq!(parsed.overall_score, 75.0);
    }

    #[test]
    fn test_markdown_contains_key_sections() {
        let result = sample_result();
        let md = to_markdown(&result);
        assert!(md.contains("# MCPSEC Benchmark Report"));
        assert!(md.contains("## Overall Score"));
        assert!(md.contains("## Property Scores"));
        assert!(md.contains("## Attack Results"));
        assert!(md.contains("## Failed Tests"));
        assert!(md.contains("## Remediation Guidance"));
        assert!(md.contains("PASS"));
        assert!(md.contains("**FAIL**"));
    }

    #[test]
    fn test_junit_output_structure() {
        let result = sample_result();
        let junit = to_junit(&result);
        assert!(junit.starts_with("<?xml version=\"1.0\""));
        assert!(junit.contains("<testsuites name=\"MCPSEC\""));
        assert!(junit.contains("tests=\"2\""));
        assert!(junit.contains("failures=\"1\""));
        assert!(junit.contains("<testsuite name=\"Prompt Injection Evasion\""));
        assert!(junit.contains("A1.1"));
        assert!(junit.contains("<failure message=\"Attack not detected\">"));
        assert!(junit.contains("</testsuites>"));
    }

    #[test]
    fn test_ocsf_output_structure() {
        let result = sample_result();
        let ocsf = to_ocsf(&result);
        let findings: Vec<serde_json::Value> = serde_json::from_str(&ocsf).unwrap();
        assert_eq!(findings.len(), 2);

        // Check OCSF class_uid = 2001 (Security Finding)
        assert_eq!(findings[0]["class_uid"], 2001);
        assert_eq!(findings[0]["class_name"], "Security Finding");

        // Passed test should have severity_id=1 (Info)
        assert_eq!(findings[0]["severity_id"], 1);
        // Failed test should have severity_id=4 (High)
        assert_eq!(findings[1]["severity_id"], 4);

        // Check finding_info
        assert_eq!(findings[0]["finding_info"]["uid"], "A1.1");
        assert_eq!(findings[1]["finding_info"]["uid"], "A1.2");

        // Check metadata
        assert_eq!(findings[0]["metadata"]["product"]["name"], "MCPSEC");
    }

    #[test]
    fn test_format_latency() {
        assert_eq!(format_latency(500), "500ns");
        assert_eq!(format_latency(28_000), "28.0us");
        assert_eq!(format_latency(1_500_000), "1.5ms");
    }
}
