/**
 * Binary download script generator.
 *
 * Produces a setup.sh that downloads the pre-built Vellaveto binary for
 * the current platform and places it in ./bin/. Self-contained — just
 * run `bash setup.sh` and the server starts.
 */

import type { WizardState, GeneratedFile } from "../types.js";
import { VERSION } from "../constants.js";

export function generateBinaryFiles(state: WizardState): GeneratedFile[] {
  return [
    {
      path: "setup.sh",
      content: generateSetupScript(state),
      description: "Download + start script for Vellaveto binary",
    },
  ];
}

function generateSetupScript(state: WizardState): string {
  return `#!/usr/bin/env bash
# Vellaveto ${VERSION} — setup script
# Generated by create-vellaveto
#
# This script downloads the Vellaveto binary for your platform,
# creates an .env file with your API key, and starts the server.
#
# Usage: bash setup.sh
set -euo pipefail

VERSION="${VERSION}"
REPO="vellaveto/vellaveto"
INSTALL_DIR="./bin"
SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"

# Detect platform
OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH="$(uname -m)"
case "\${ARCH}" in
  x86_64|amd64) ARCH="x86_64" ;;
  aarch64|arm64) ARCH="aarch64" ;;
  *) echo "Error: Unsupported architecture: \${ARCH}" >&2; exit 1 ;;
esac

case "\${OS}" in
  linux)  TARGET="\${ARCH}-unknown-linux-gnu" ;;
  darwin) TARGET="\${ARCH}-apple-darwin" ;;
  *)      echo "Error: Unsupported OS: \${OS}" >&2; exit 1 ;;
esac

TARBALL="vellaveto-\${VERSION}-\${TARGET}.tar.gz"
URL="https://github.com/\${REPO}/releases/download/v\${VERSION}/\${TARBALL}"

echo "==> Downloading Vellaveto \${VERSION} for \${TARGET}..."
mkdir -p "\${INSTALL_DIR}"
if ! curl -fsSL "\${URL}" -o "/tmp/\${TARBALL}"; then
  echo ""
  echo "Error: Download failed. Check that version \${VERSION} has a release for \${TARGET}."
  echo "  URL: \${URL}"
  exit 1
fi

echo "==> Extracting to \${INSTALL_DIR}/..."
tar -xzf "/tmp/\${TARBALL}" -C "\${INSTALL_DIR}"
rm -f "/tmp/\${TARBALL}"
chmod +x "\${INSTALL_DIR}/vellaveto" "\${INSTALL_DIR}/vellaveto-http-proxy" 2>/dev/null || true

# Write .env if it doesn't exist
if [ ! -f "\${SCRIPT_DIR}/.env" ]; then
  cat > "\${SCRIPT_DIR}/.env" << 'ENVEOF'
# Vellaveto environment variables — do not commit this file
VELLAVETO_API_KEY=${state.apiKey}${state.checkpointInterval > 0 ? `\nVELLAVETO_CHECKPOINT_INTERVAL=${state.checkpointInterval}` : ""}
ENVEOF
  echo "==> Wrote .env"
fi

echo ""
echo "Vellaveto is ready!"
echo ""
echo "Start the server:"
echo "  cd \${SCRIPT_DIR}"
echo "  source .env"
echo "  \${INSTALL_DIR}/vellaveto serve --config vellaveto.toml"
echo ""
echo "Or start the HTTP proxy:"
echo "  \${INSTALL_DIR}/vellaveto-http-proxy serve --config vellaveto.toml"
`;
}
