/**
 * Kubernetes / Helm values generator.
 *
 * Produces a vellaveto-values.yaml for `helm install -f` and a
 * vellaveto-configmap.yaml for applying the TOML config via kubectl.
 */

import type { WizardState, GeneratedFile } from "../types.js";
import { IMAGE_TAG } from "../constants.js";
import { generateToml } from "./toml.js";

export function generateHelmFiles(state: WizardState): GeneratedFile[] {
  return [
    {
      path: "vellaveto-values.yaml",
      content: generateValues(state),
      description: "Helm values override for Vellaveto chart",
    },
    {
      path: "vellaveto-configmap.yaml",
      content: generateConfigMap(state),
      description: "Kubernetes ConfigMap with Vellaveto TOML config",
    },
  ];
}

function generateValues(state: WizardState): string {
  let yaml = "";
  yaml += "# Vellaveto Helm values — generated by setup wizard\n";
  yaml += "# Usage: helm install vellaveto oci://ghcr.io/paolovella/vellaveto/chart -f vellaveto-values.yaml\n\n";

  yaml += `image:\n`;
  yaml += `  tag: "${IMAGE_TAG}"\n\n`;

  yaml += "securityContext:\n";
  yaml += "  runAsNonRoot: true\n";
  yaml += "  runAsUser: 1000\n";
  yaml += "  runAsGroup: 1000\n";
  yaml += "  readOnlyRootFilesystem: true\n";
  yaml += "  allowPrivilegeEscalation: false\n";
  yaml += "  capabilities:\n";
  yaml += "    drop:\n";
  yaml += "      - ALL\n\n";

  yaml += "resources:\n";
  yaml += "  limits:\n";
  yaml += "    cpu: 500m\n";
  yaml += "    memory: 128Mi\n";
  yaml += "  requests:\n";
  yaml += "    cpu: 100m\n";
  yaml += "    memory: 64Mi\n\n";

  yaml += "vellaveto:\n";
  yaml += "  logLevel: info\n";
  yaml += "  strictMode: true\n\n";

  yaml += "  injection:\n";
  yaml += `    enabled: ${state.injectionEnabled}\n`;
  yaml += `    blocking: ${state.injectionBlocking}\n\n`;

  yaml += "  dlp:\n";
  yaml += `    enabled: ${state.dlpEnabled}\n`;
  yaml += `    blocking: ${state.dlpBlocking}\n\n`;

  yaml += "  audit:\n";
  yaml += `    redactionLevel: "${capitalize(state.redactionLevel)}"\n\n`;

  yaml += "  # API key should be provided via Kubernetes Secret:\n";
  yaml += "  #   kubectl create secret generic vellaveto-api-key --from-literal=api-key=<YOUR_KEY>\n";
  yaml += "  extraEnv:\n";
  yaml += "    - name: VELLAVETO_API_KEY\n";
  yaml += "      valueFrom:\n";
  yaml += "        secretKeyRef:\n";
  yaml += "          name: vellaveto-api-key\n";
  yaml += "          key: api-key\n\n";

  yaml += "metrics:\n";
  yaml += "  enabled: true\n";
  yaml += "  serviceMonitor:\n";
  yaml += "    enabled: false\n\n";

  yaml += "probes:\n";
  yaml += "  liveness:\n";
  yaml += "    enabled: true\n";
  yaml += "  readiness:\n";
  yaml += "    enabled: true\n";

  return yaml;
}

function generateConfigMap(state: WizardState): string {
  const toml = generateToml(state);
  // Indent each TOML line by 4 spaces for the ConfigMap data block
  const indented = toml
    .split("\n")
    .map((line) => (line ? `    ${line}` : ""))
    .join("\n");

  let yaml = "";
  yaml += "# Vellaveto ConfigMap — generated by setup wizard\n";
  yaml += "# Usage: kubectl apply -f vellaveto-configmap.yaml\n";
  yaml += "apiVersion: v1\n";
  yaml += "kind: ConfigMap\n";
  yaml += "metadata:\n";
  yaml += "  name: vellaveto-config\n";
  yaml += "  labels:\n";
  yaml += "    app.kubernetes.io/name: vellaveto\n";
  yaml += "    app.kubernetes.io/component: config\n";
  yaml += "data:\n";
  yaml += "  config.toml: |\n";
  yaml += indented;
  yaml += "\n";

  return yaml;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
