/**
 * TOML configuration generator.
 *
 * Output must match vellaveto-server/src/setup_wizard.rs generate_config_toml()
 * (lines ~1596-1844) so configs are interchangeable between the web wizard and
 * this CLI wizard.
 */

import type { WizardState } from "../types.js";
import { escapeTomlString } from "../utils.js";

/** Map wizard redaction level names to server-accepted values. */
function mapRedactionLevel(level: string): string {
  switch (level) {
    case "off":
      return "Off";
    case "low":
      return "KeysOnly";
    case "high":
      return "KeysAndPatterns";
    default:
      return level;
  }
}

export function generateToml(state: WizardState): string {
  let toml = "";

  // Header
  toml += "# Vellaveto Configuration\n";
  toml += "# Generated by the setup wizard\n\n";

  // API key note
  if (state.apiKey) {
    toml +=
      "# API key configured via wizard — set VELLAVETO_API_KEY environment variable\n\n";
  }

  // CORS origins
  if (state.corsOrigins.length > 0) {
    toml +=
      "# Allowed CORS origins (also settable via VELLAVETO_CORS_ORIGINS env var)\n";
    toml += "allowed_origins = [";
    for (let i = 0; i < state.corsOrigins.length; i++) {
      if (i > 0) toml += ", ";
      toml += `"${escapeTomlString(state.corsOrigins[i])}"`;
    }
    toml += "]\n\n";
  }

  // Policies
  toml += "# ─── Policies ───────────────────────────────────────────────\n\n";
  toml += generatePolicyPreset(state.policyPreset);

  // Detection
  toml += "# ─── Detection ──────────────────────────────────────────────\n\n";
  toml += "[injection]\n";
  toml += `enabled = ${state.injectionEnabled}\n`;
  if (state.injectionEnabled) {
    toml += `block_on_injection = ${state.injectionBlocking}\n`;
  }
  toml += "\n";

  toml += "[dlp]\n";
  toml += `enabled = ${state.dlpEnabled}\n`;
  if (state.dlpEnabled) {
    toml += `block_on_finding = ${state.dlpBlocking}\n`;
  }
  toml += "\n";

  if (state.behavioralEnabled) {
    toml += "[behavioral]\n";
    toml += "enabled = true\n\n";
  }

  // Audit
  toml += "# ─── Audit ──────────────────────────────────────────────────\n\n";
  toml += "[audit]\n";
  toml += `redaction_level = "${escapeTomlString(mapRedactionLevel(state.redactionLevel))}"\n`;
  toml += "\n";
  if (state.checkpointInterval > 0) {
    toml += `# Checkpoint interval: set VELLAVETO_CHECKPOINT_INTERVAL=${state.checkpointInterval} env var\n\n`;
  }

  // Audit export
  if (state.auditExportFormat !== "none") {
    // Map "webhook" format to "jsonl" (webhook is delivery, not format)
    const exportFormat = state.auditExportFormat === "webhook" ? "jsonl" : state.auditExportFormat;
    toml += "[audit_export]\n";
    toml += `format = "${escapeTomlString(exportFormat)}"\n`;
    // webhook_url is only valid for webhook delivery (must be https://)
    if (state.auditExportFormat === "webhook" && state.auditExportTarget) {
      toml += `webhook_url = "${escapeTomlString(state.auditExportTarget)}"\n`;
    } else if (state.auditExportTarget && state.auditExportFormat !== "webhook") {
      toml += `# Export file: ${escapeTomlString(state.auditExportTarget)}\n`;
    }
    toml += "\n";
  }

  // Compliance
  const hasCompliance = state.complianceFrameworks.length > 0;
  if (hasCompliance) {
    toml +=
      "# ─── Compliance ─────────────────────────────────────────────\n\n";
    toml += "[compliance]\n";

    if (state.complianceFrameworks.includes("eu_ai_act")) {
      toml += "\n[compliance.eu_ai_act]\n";
      toml += "enabled = true\n";
      toml += "transparency_marking = true\n";
    }
    if (state.complianceFrameworks.includes("soc2")) {
      toml += "\n[compliance.soc2]\n";
      toml += "enabled = true\n";
    }
    if (state.complianceFrameworks.includes("iso42001")) {
      toml +=
        "\n# ISO 42001 compliance enabled — AI management system controls active\n";
    }
    if (state.complianceFrameworks.includes("nis2")) {
      toml +=
        "\n# NIS2 compliance enabled — incident reporting and supply chain checks active\n";
    }
    if (state.complianceFrameworks.includes("dora")) {
      toml +=
        "\n# DORA compliance enabled — ICT risk management and incident tracking active\n";
    }
    toml += "\n";
  }

  return toml;
}

function generatePolicyPreset(preset: WizardState["policyPreset"]): string {
  switch (preset) {
    case "strict":
      return generateStrictPreset();
    case "balanced":
      return generateBalancedPreset();
    case "permissive":
      return generatePermissivePreset();
  }
}

function generateStrictPreset(): string {
  let toml = "";
  toml +=
    "# Policy preset: Strict (deny-by-default, maximum security)\n\n";

  // Default deny
  toml += "[[policies]]\n";
  toml += 'id = "default-deny"\n';
  toml += 'name = "Default deny all"\n';
  toml += 'policy_type = "Deny"\n';
  toml += "priority = 0\n";
  toml += 'tool = "*"\n';
  toml += 'function = "*"\n\n';

  // Block credentials
  toml += "[[policies]]\n";
  toml += 'id = "block-credentials"\n';
  toml += 'name = "Block credential access"\n';
  toml += 'policy_type = "Deny"\n';
  toml += "priority = 100\n";
  toml += 'tool = "*"\n';
  toml += 'function = "*"\n\n';
  toml += "[policies.path_rules]\n";
  toml +=
    'blocked_patterns = ["**/.env", "**/*.key", "**/*.pem", "**/credentials*", "**/.ssh/**", "**/.aws/**"]\n\n';

  // Block exfiltration
  toml += "[[policies]]\n";
  toml += 'id = "block-exfiltration"\n';
  toml += 'name = "Block data exfiltration"\n';
  toml += 'policy_type = "Deny"\n';
  toml += "priority = 100\n";
  toml += 'tool = "*"\n';
  toml += 'function = "*"\n\n';
  toml += "[policies.network_rules]\n";
  toml +=
    'blocked_domains = ["*.pastebin.com", "*.transfer.sh", "*.ngrok.io"]\n\n';

  // Require approval for destructive
  toml += "[[policies]]\n";
  toml += 'id = "approve-destructive"\n';
  toml += 'name = "Require approval for destructive operations"\n';
  toml += 'policy_type = "RequireApproval"\n';
  toml += "priority = 50\n";
  toml += 'tool = "*"\n';
  toml += 'function = "*"\n\n';
  toml += "[policies.path_rules]\n";
  toml += 'write_patterns = ["**/*"]\n\n';

  return toml;
}

function generateBalancedPreset(): string {
  let toml = "";
  toml +=
    "# Policy preset: Balanced (deny-by-default, read allowed, writes require approval)\n\n";

  // Default deny
  toml += "[[policies]]\n";
  toml += 'id = "default-deny"\n';
  toml += 'name = "Default deny all"\n';
  toml += 'policy_type = "Deny"\n';
  toml += "priority = 0\n";
  toml += 'tool = "*"\n';
  toml += 'function = "*"\n\n';

  // Block credentials
  toml += "[[policies]]\n";
  toml += 'id = "block-credentials"\n';
  toml += 'name = "Block credential access"\n';
  toml += 'policy_type = "Deny"\n';
  toml += "priority = 100\n";
  toml += 'tool = "*"\n';
  toml += 'function = "*"\n\n';
  toml += "[policies.path_rules]\n";
  toml +=
    'blocked_patterns = ["**/.env", "**/*.key", "**/*.pem", "**/credentials*", "**/.ssh/**", "**/.aws/**"]\n\n';

  // Allow reads
  toml += "[[policies]]\n";
  toml += 'id = "allow-reads"\n';
  toml += 'name = "Allow file reads"\n';
  toml += 'policy_type = "Allow"\n';
  toml += "priority = 50\n";
  toml += 'tool = "*"\n';
  toml += 'function = "read*"\n\n';

  // Require approval for writes
  toml += "[[policies]]\n";
  toml += 'id = "approve-writes"\n';
  toml += 'name = "Require approval for file writes"\n';
  toml += 'policy_type = "RequireApproval"\n';
  toml += "priority = 50\n";
  toml += 'tool = "*"\n';
  toml += 'function = "write*"\n\n';

  return toml;
}

function generatePermissivePreset(): string {
  let toml = "";
  toml +=
    "# Policy preset: Permissive (allow-by-default, block credentials and exfiltration)\n\n";

  // Default allow
  toml += "[[policies]]\n";
  toml += 'id = "default-allow"\n';
  toml += 'name = "Default allow all"\n';
  toml += 'policy_type = "Allow"\n';
  toml += "priority = 0\n";
  toml += 'tool = "*"\n';
  toml += 'function = "*"\n\n';

  // Block credentials
  toml += "[[policies]]\n";
  toml += 'id = "block-credentials"\n';
  toml += 'name = "Block credential access"\n';
  toml += 'policy_type = "Deny"\n';
  toml += "priority = 100\n";
  toml += 'tool = "*"\n';
  toml += 'function = "*"\n\n';
  toml += "[policies.path_rules]\n";
  toml +=
    'blocked_patterns = ["**/.env", "**/*.key", "**/*.pem", "**/credentials*", "**/.ssh/**", "**/.aws/**"]\n\n';

  // Block exfiltration
  toml += "[[policies]]\n";
  toml += 'id = "block-exfiltration"\n';
  toml += 'name = "Block data exfiltration"\n';
  toml += 'policy_type = "Deny"\n';
  toml += "priority = 100\n";
  toml += 'tool = "*"\n';
  toml += 'function = "*"\n\n';
  toml += "[policies.network_rules]\n";
  toml +=
    'blocked_domains = ["*.pastebin.com", "*.transfer.sh", "*.ngrok.io"]\n\n';

  return toml;
}
