name: OpenSSF Scorecard

on:
  push:
    branches: [main]
  schedule:
    # Every Monday at 07:00 UTC
    - cron: "0 7 * * 1"
  workflow_dispatch:

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analysis:
    name: Scorecard Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      actions: read
      contents: read
      issues: read
      pull-requests: read
      checks: read
      security-events: write
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: scorecard.sarif
          results_format: sarif
          publish_results: true

      - name: Upload Scorecard artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: scorecard-sarif
          path: scorecard.sarif
          if-no-files-found: error

      - name: Upload Scorecard SARIF
        if: ${{ github.event.repository.private == false || vars.ENABLE_CODE_SCANNING == 'true' }}
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@89a39a4e59826350b863aa6b6252a07ad50cf83e # v3
        with:
          sarif_file: scorecard.sarif
